apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-west-2

vpc:
  id: "vpc-0efc93a10f2148f0a"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-west-2a: { id: subnet-0a72788c90dabe408 }
      us-west-2b: { id: subnet-0a78ee5dffd8b3a82 }
      us-west-2c: { id: subnet-03f12e1f229ff641e }

managedNodeGroups:
  # - name: ng1-public
  #   instanceType: t3.small
  #   desiredCapacity: 3
  #   labels: { role: workers }
  #   ssh: 
  #     allow: true
  #     publicKeyName: scriptcamp
  #   tags:
  #     Name: eks-ng01
  # - name: ng-spot-01
  #   instanceType: t3.small
  #   labels: { role: builders }
  #   minSize: 3
  #   maxSize: 6
  #   spot: true
  #   ssh: 
  #     allow: true
  #     publicKeyName: scriptcamp
  #   tags:
  #     Name: ng-spot

  - name: ng-spot-02
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 3
    maxSize: 6
    spot: true
    ssh: 
      allow: true
      publicKeyName: techiescamp
    tags:
      Name: ng-spot

# cloudWatch:
#   clusterLogging:
#     enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler" ]
