apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-west-2

vpc:
  id: "vpc-0e2bf0b3041ce31eb"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-west-2a: { id: subnet-0bcbbae28398fc9c8 }
      us-west-2b: { id: subnet-0f0a2f71f677ad146 }
      us-west-2c: { id: subnet-02bf598632bbeb39e }

managedNodeGroups:
  - name: ng1-public
    instanceType: t3.small
    desiredCapacity: 3
    ssh: 
      allow: true
      publicKeyName: scriptcamp
    tags:
      Name: eks-ng01
      # kubernetes.io/cluster/eks-spot-cluster: owned
nodeGroups:
  - name: ng-01-spot
    minSize: 2
    maxSize: 6
    instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small", "t3.medium"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        SpotAllocationStrategy: "capacity-optimized"
    ssh: 
      allow: true
      publicKeyName: scriptcamp
    tags:
      Name: eks-spot-01
      kubernetes.io/cluster/eks-spot-cluster: owned